import React from 'react'
import Head from 'next/head'
import MyApp from './_app'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Pedro Elton's front-end developer's portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <MyApp/>

    </div>
  )
}
